
START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'idmgmt') THEN
        CREATE SCHEMA idmgmt;
    END IF;
END $EF$;

CREATE TABLE idmgmt.device_codes (
    user_code character varying(200) NOT NULL,
    device_code character varying(200) NOT NULL,
    subject_id character varying(200),
    session_id character varying(100),
    client_id character varying(200) NOT NULL,
    description character varying(200),
    creation_time timestamp with time zone NOT NULL,
    expiration timestamp with time zone NOT NULL,
    data character varying(50000) NOT NULL,
    CONSTRAINT pk_device_codes PRIMARY KEY (user_code)
);

CREATE TABLE idmgmt.keys (
    id text NOT NULL,
    version integer NOT NULL,
    created timestamp with time zone NOT NULL,
    use text,
    algorithm character varying(100) NOT NULL,
    is_x509_certificate boolean NOT NULL,
    data_protected boolean NOT NULL,
    data text NOT NULL,
    CONSTRAINT pk_keys PRIMARY KEY (id)
);

CREATE TABLE idmgmt.persisted_grants (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    key character varying(200),
    type character varying(50) NOT NULL,
    subject_id character varying(200),
    session_id character varying(100),
    client_id character varying(200) NOT NULL,
    description character varying(200),
    creation_time timestamp with time zone NOT NULL,
    expiration timestamp with time zone,
    consumed_time timestamp with time zone,
    data character varying(50000) NOT NULL,
    CONSTRAINT pk_persisted_grants PRIMARY KEY (id)
);

CREATE TABLE idmgmt.pushed_authorization_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    reference_value_hash character varying(64) NOT NULL,
    expires_at_utc timestamp with time zone NOT NULL,
    parameters text NOT NULL,
    CONSTRAINT pk_pushed_authorization_requests PRIMARY KEY (id)
);

CREATE TABLE idmgmt.server_side_sessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    key character varying(100) NOT NULL,
    scheme character varying(100) NOT NULL,
    subject_id character varying(100) NOT NULL,
    session_id character varying(100),
    display_name character varying(100),
    created timestamp with time zone NOT NULL,
    renewed timestamp with time zone NOT NULL,
    expires timestamp with time zone,
    data text NOT NULL,
    CONSTRAINT pk_server_side_sessions PRIMARY KEY (id)
);

CREATE UNIQUE INDEX ix_device_codes_device_code ON idmgmt.device_codes (device_code);

CREATE INDEX ix_device_codes_expiration ON idmgmt.device_codes (expiration);

CREATE INDEX ix_keys_use ON idmgmt.keys (use);

CREATE INDEX ix_persisted_grants_consumed_time ON idmgmt.persisted_grants (consumed_time);

CREATE INDEX ix_persisted_grants_expiration ON idmgmt.persisted_grants (expiration);

CREATE UNIQUE INDEX ix_persisted_grants_key ON idmgmt.persisted_grants (key);

CREATE INDEX ix_persisted_grants_subject_id_client_id_type ON idmgmt.persisted_grants (subject_id, client_id, type);

CREATE INDEX ix_persisted_grants_subject_id_session_id_type ON idmgmt.persisted_grants (subject_id, session_id, type);

CREATE INDEX ix_pushed_authorization_requests_expires_at_utc ON idmgmt.pushed_authorization_requests (expires_at_utc);

CREATE UNIQUE INDEX ix_pushed_authorization_requests_reference_value_hash ON idmgmt.pushed_authorization_requests (reference_value_hash);

CREATE INDEX ix_server_side_sessions_display_name ON idmgmt.server_side_sessions (display_name);

CREATE INDEX ix_server_side_sessions_expires ON idmgmt.server_side_sessions (expires);

CREATE UNIQUE INDEX ix_server_side_sessions_key ON idmgmt.server_side_sessions (key);

CREATE INDEX ix_server_side_sessions_session_id ON idmgmt.server_side_sessions (session_id);

CREATE INDEX ix_server_side_sessions_subject_id ON idmgmt.server_side_sessions (subject_id);

COMMIT;
